permalink: /p/:year/:month/:day/:title
pygments: true

title: blog.gehtnicht.at
baseurl: /
url: http://blog.gehtnicht.at

excerpt_separator: <!--break-->
paginate: 10
paginate_path: "index/:num"

exclude: ['*.lnk', '*.debug.html']
images: /files

encoding: utf-8
markdown: kramdown
