version: '3'
services:
  web:
    image: nginx:1.19.2-alpine
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80

  build:
    image: jekyll/jekyll:3.8
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: jekyll build --watch

  bundle-update:
    image: jekyll/jekyll:3.8
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command: bundle update
